version: '3'

services:
  app:
    image: 'license_management_api:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: license_management_api
    depends_on:
      - db
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/license_management
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"